version: 2
    
jobs:
  deploy:
    docker:
      - image: circleci/node:11.11.0
      
    steps:
      - checkout
      - run:
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email "CipherWang@users.noreply.github.com"
            git config --global user.name "CipherWang"
            echo "machine github.com login CipherWang password $GITHUB_TOKEN" > ~/.netrc
            cd website && yarn install && GIT_USER=CipherWang yarn run publish-gh-pages

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
